# Generated by Django 5.1.5 on 2025-02-04 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
