# Generated by Django 5.1.5 on 2025-02-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ticket_age_alter_ticket_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_seat',
            name='booked_seats',
        ),
    ]
