# Generated by Django 5.1.5 on 2025-02-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_route_seat_booked_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='old_verified',
            field=models.BooleanField(default=False),
        ),
    ]
